### ISSUE TITLE
invalid character?

### ISSUE THREAD

**Issue by tuupos** [sebmatton/TeslaApiTokenGenerator#1]
I get the following error at line 102:

 <title>TeslaApiTokenGenerator/TeslaApiTokenGenerator.py at main · sebmatton/TeslaApiTokenGenerator</title>

Where the  "·" seems to be the error

How can I solve this?

**Comment by tuupos** [comment]
after downloading it in a zip file and extracting the code  I get the following error:

![image](https://github.com/sebmatton/TeslaApiTokenGenerator/assets/54961501/fe991837-33df-497f-b2e7-62725f74298b)

**Comment by pbathuk** [comment]
Hi, 
I have submitted an update to the readme to help on this. 
The script requires the requests library, which is not installed by default on a fresh python. 

A quick Google should show you how to install requests via pip or another means. 

Once installed, the script should work for you - I know that was an issue I faced. 

Cheers

**Comment by sebmatton** [comment]
This documentation was updated, thanks @pbathuk

**Comment by tuupos** [comment]
> Hi, I have submitted an update to the readme to help on this. The script requires the requests library, which is not installed by default on a fresh python.
> 
> A quick Google should show you how to install requests via pip or another means.
> 
> Once installed, the script should work for you - I know that was an issue I faced.
> 
> Cheers

Thank you very much!!!
